default:
  tags: ['smp-runner-shell']

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag="$CI_COMMIT_TAG" "https://gitlab.ecedi.fr/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
  only:
    - tags
