default:
  tags: [ 'smp-runner-docker' ]

stages:
  - build
  - test
  - quality
  - deploy

build:
  stage: build
  image: $CI_REGISTRY/simplonprod/devops/docker-images/php/8.0
  script:
    - composer2 config -g cache-dir "$(pwd)/.composer-cache"
    - composer2 install
  artifacts:
    paths:
      - vendor
  allow_failure: false
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME-php"
    policy: pull-push
    paths:
      - vendor
      - .composer-cache
  only:
    - master

test:
  stage: test
  image: $CI_REGISTRY/simplonprod/devops/docker-images/php/8.0-xdebug
  services:
    - mysql:5.7
  variables:
    # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: "db"
    MYSQL_USER: "db"
    MYSQL_PASSWORD: "db"
    MYSQL_ROOT_PASSWORD: "db"
  before_script:
    - cp tests/example-env tests/.env
  script:
    - ./vendor/bin/codecept run --no-colors --steps --xml --html --coverage --coverage-xml --coverage-html
  artifacts:
    paths:
      - tests/_output/report.xml
      - tests/_output/report.html
      - tests/_output/coverage.xml
      - tests/_output/coverage
    reports:
      junit: tests/_output/report.xml
  only:
    - master

sonarqube_issues:
  image: ciricihq/gitlab-sonar-scanner
  stage: quality
  variables:
    SONAR_URL: https://sonar.ecedi.net
    SONAR_ANALYSIS_MODE: issues
  script:
    - gitlab-sonar-scanner -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONARQUBE_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_URL
  allow_failure: true
  only:
    - master

deploy:
  image: curlimages/curl
  stage: deploy
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag="$CI_COMMIT_TAG" "https://gitlab.ecedi.fr/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
  only:
    - tags

pages:
  image: alpine:latest
  stage: deploy
  script:
    - mkdir .public
    - cp -r tests/_output/coverage .public/coverage
    - cp tests/_output/report.html .public/index.html
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master

sonarqube_publish:
  image: ciricihq/gitlab-sonar-scanner
  stage: deploy
  variables:
    SONAR_URL: https://sonar.ecedi.net
    SONAR_ANALYSIS_MODE: publish
  script:
    - gitlab-sonar-scanner -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONARQUBE_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_URL
  only:
    - master

